#!/usr/bin/env bash
# How to install nginx on a remote server and configure it
sudo apt update 
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo service nginx restart
